@startuml

skinparam backgroundColor #FEFEFE

[Inference] as inf
[Network] as net
[Buffer] as buf
[Device] as dev

inf -> net
inf -> buf: IFM and OFM

net --> dev
net --> buf: Network model

buf -> dev

@enduml